### ISSUE TITLE
Avogadro 2 Plugin Error

### ISSUE THREAD

**Issue by Dfilono** [Dfilono/TurtleMol#6]
The file [densitySphere.py](https://github.com/Dfilono/TurtleMol/blob/main/TurtleMol/avogadroPlugin/densitySphere.py) file is for some reason returning the below error when generating a new XYZ file.

![image](https://github.com/Dfilono/TurtleMol/assets/56603954/4a1132ff-9a4c-42a1-b6c9-4d2ae4fdb535)

This error occurs even if the structure pulled from Avogadro is fed back into it. I am unsure as to where exactly the issue is, since debugging has demonstrated that this function is not generating files any differently than the others in the plugin. 

The xyz files generated from the same Sphere function, one just considering density and the other not, have both been attached. Only the density xyz will not work via the plugin, but the actually generated file does load correctly in Avogadro.

[densitySphere.txt](https://github.com/Dfilono/TurtleMol/files/13405112/densitySphere.txt)
[fillSphere.txt](https://github.com/Dfilono/TurtleMol/files/13405113/fillSphere.txt)

**Comment by ghutchis** [comment]
It looks like there are two newlines, then "19" then a newline, then the JSON. Is something printing before the JSON is dumped?

**Comment by Dfilono** [comment]
There was a rogue print statement hidden deep in the code I had missed! Thank you! This was bugging me for days!
